---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)

library(plotly)
```


```{r loading the dataset}
library(dplyr)
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "SNOW", "SNWD", "TMAX", "TMIN"),
    date_min = "2020-01-01",
    date_max = "2020-12-31") %>%
  mutate(name = recode(id, USW00094728 = "CentralParkNY")) %>%
    separate(date,into = c("year","month","date"),sep = "-",remove = TRUE,extra = "warn") %>%
  mutate(
    month = recode(month,'01' = "january", '02' = "february", '03' = "march", '04' = "april", '05' = "may", '06' = "june",'07' = "july", '08' = "august", '09' = "september", '10' = "october", '11' = "november", '12' = "december"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    prcp = prcp / 10) %>%
  select(name, id, everything())
```

Column {data-width=500}
-----------------------------------------------------------------------

### Chart A

```{r}
weather_df %>%
   mutate(month = fct_inorder(month)) %>%
  plot_ly(y = ~tmax, color = ~month, type = "box", colors = "viridis")
```

Column {data-width=500}
-----------------------------------------------------------------------

### Chart B

```{r}
weather_df %>%
   mutate(month = fct_inorder(month)) %>%
  plot_ly(
    x = ~tmin, y = ~tmax, type = "scatter", mode = "markers", 
    color = ~month ,text = ~date)
```

### Chart C

```{r}
weather_df %>%
     mutate(month = fct_inorder(month)) %>%
  plot_ly(
    x = ~month, y = ~prcp, type = "violin", mode = "markers",
    color = ~month, text = ~date)
```


